name: Django Tests


on:
  push:
    brances:
      - master
  pull_request:
    brances: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Testing
        run: |
          python3 manage.py test




        
